# Site settings
title: This Is A test
header-img: img/home-bg.png
email: sabrina.jones87@gmail.com
copyright_name: sabrina-jones
description: > # this means to ignore newlines until "baseurl:"
  This is only a test
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sabrina-jones
learn_profile: sabrina-jones
email_username: sabrina.jones87@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
